In [66]:
import matplotlib.pyplot as plt
import tensorflow as tf
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder , OneHotEncoder
tf.compat.v1.disable_eager_execution()

In [67]:
import os
os.getcwd()

'C:\\Users\\pmgho\\OneDrive\\Desktop\\Prajwal_capstone_sql_project'

In [68]:
os.chdir('C:\\Users\\pmgho\\OneDrive\\Desktop\\Prajwal_capstone_sql_project')

In [69]:
df = pd.read_csv('sonar.csv',header=None)
display(df)

,0,1,2,3,4,5,6,7,8,9,...,51,52,53,54,55,56,57,58,59,60
0,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032,R
1,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,0.2872,...,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044,R
2,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,0.6194,...,0.0232,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078,R
3,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,0.1264,...,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117,R
4,0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,0.4459,...,0.0031,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094,R
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203,0.0187,0.0346,0.0168,0.0177,0.0393,0.1630,0.2028,0.1694,0.2328,0.2684,...,0.0116,0.0098,0.0199,0.0033,0.0101,0.0065,0.0115,0.0193,0.0157,M
204,0.0323,0.0101,0.0298,0.0564,0.0760,0.0958,0.0990,0.1018,0.1030,0.2154,...,0.0061,0.0093,0.0135,0.0063,0.0063,0.0034,0.0032,0.0062,0.0067,M
205,0.0522,0.0437,0.0180,0.0292,0.0351,0.1171,0.1257,0.1178,0.1258,0.2529,...,0.0160,0.0029,0.0051,0.0062,0.0089,0.0140,0.0138,0.0077,0.0031,M
206,0.0303,0.0353,0.0490,0.0608,0.0167,0.1354,0.1465,0.1123,0.1945,0.2354,...,0.0086,0.0046,0.0126,0.0036,0.0035,0.0034,0.0079,0.0036,0.0048,M
207,0.0260,0.0363,0.0136,0.0272,0.0214,0.0338,0.0655,0.1400,0.1843,0.2354,...,0.0146,0.0129,0.0047,0.0039,0.0061,0.0040,0.0036,0.0061,0.0115,M

In [70]:
print(len(df.columns))

61

In [71]:
df.shape

(208, 61)

In [72]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,51,52,53,54,55,56,57,58,59,60
0,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032,R
1,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,0.2872,...,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044,R
2,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,0.6194,...,0.0232,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078,R
3,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,0.1264,...,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117,R
4,0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,0.4459,...,0.0031,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094,R

In [73]:
X = df[df.columns[0:60]].values
y=df[df.columns[60]]
X

array([[0.02  , 0.0371, 0.0428, ..., 0.0084, 0.009 , 0.0032],
       [0.0453, 0.0523, 0.0843, ..., 0.0049, 0.0052, 0.0044],
       [0.0262, 0.0582, 0.1099, ..., 0.0164, 0.0095, 0.0078],
       ...,
       [0.0522, 0.0437, 0.018 , ..., 0.0138, 0.0077, 0.0031],
       [0.0303, 0.0353, 0.049 , ..., 0.0079, 0.0036, 0.0048],
       [0.026 , 0.0363, 0.0136, ..., 0.0036, 0.0061, 0.0115]])

In [74]:
y

0      R
1      R
2      R
3      R
4      R
      ..
203    M
204    M
205    M
206    M
207    M
Name: 60, Length: 208, dtype: object

In [75]:
from sklearn.preprocessing import LabelEncoder
y_labelencoder = LabelEncoder ()
y = y_labelencoder.fit_transform (y)
print (y)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

In [78]:
from sklearn.preprocessing import LabelEncoder
import tensorflow as tf

# label encode
le = LabelEncoder()
y = le.fit_transform(y)

# one-hot encode
Y = tf.keras.utils.to_categorical(y, num_classes=2)
Y

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [20]:
from sklearn.preprocessing import OneHotEncoder
y = y.reshape(-1, 1)
onehotencoder = OneHotEncoder(sparse_output=False)
Y = onehotencoder.fit_transform(y)
print(Y)

[[0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]]

In [79]:
train_x,test_x,train_y,test_y = train_test_split(X,Y,test_size=0.20, random_state=42)
#print the shape of the train and test data values
print(train_x.shape)
print(train_y.shape)
print(test_x.shape)
print(test_y.shape)

(166, 60)
(166, 2)
(42, 60)
(42, 2)

In [80]:
train_x = train_x.astype(np.float32)
test_x = test_x.astype(np.float32)
train_y = train_y.astype(np.float32)
test_y = test_y.astype(np.float32)

In [81]:
learning_rate = 0.01
training_epochs = 100
cost_history = np.empty(shape=[1],dtype=float)

In [82]:
n_class = 2 # Rock and Mine

x = tf.compat.v1.placeholder(tf.float32,[None,60])

W = tf.Variable(tf.zeros([60,n_class]))  
 
b = tf.Variable(tf.zeros([n_class]))

In [83]:
#initialize all variables.
#init = tf.global_variables_initializer()
init = tf.compat.v1.global_variables_initializer()

In [84]:
y = tf.compat.v1.placeholder(tf.float32,[None,n_class])  # actual y
pred = tf.nn.softmax(tf.matmul(x, W)+ b)  # predicted y

In [85]:
cost_function = tf.reduce_mean(-tf.reduce_sum((y * tf.math.log(pred)))) # calculating rmse

In [86]:
#tf.compat.v1.disable_v2_behavior()
training_step = tf.compat.v1.train.GradientDescentOptimizer(learning_rate).minimize(cost_function)

In [87]:
#initialize the session
sess = tf.compat.v1.Session()
sess.run(init)
mse_history = []

In [88]:
#calculate the cost for each epoch
for i in range(100):
    sess.run(training_step,feed_dict=({x: train_x, y: train_y}))
    cost = sess.run(cost_function,feed_dict={x: train_x,y:train_y})
    cost_history = np.append(cost_history,cost) #cost history we have created previously and using it here just to store the cost of each epoch

    #after above 3 lines weights get updated and once we have updated weights we will evaluate the test data set. 

    pred_y = sess.run(pred, feed_dict={x: test_x})  # y is a linear model which is using softmax function. Once we update the weights we will evaluate it on the test_x
    print('epoch : ', i,  ' - ', 'cost: ', cost)  # printing cost or error associated with each epoch
    
    # we want to calculate the mean square error now
    mse = tf.reduce_mean(tf.square(pred_y - test_y))  # test_y is the actual output and pred_y is the predicted output
    mse_history.append(sess.run(mse))

epoch :  0  -  cost:  117.10056
epoch :  1  -  cost:  297.08435
epoch :  2  -  cost:  857.89905
epoch :  3  -  cost:  253.21394
epoch :  4  -  cost:  838.732
epoch :  5  -  cost:  253.43784
epoch :  6  -  cost:  820.8214
epoch :  7  -  cost:  253.01488
epoch :  8  -  cost:  799.3465
epoch :  9  -  cost:  256.63477
epoch :  10  -  cost:  776.8246
epoch :  11  -  cost:  261.66528
epoch :  12  -  cost:  752.83057
epoch :  13  -  cost:  268.38766
epoch :  14  -  cost:  727.9611
epoch :  15  -  cost:  276.00476
epoch :  16  -  cost:  702.34576
epoch :  17  -  cost:  284.0862
epoch :  18  -  cost:  676.3038
epoch :  19  -  cost:  291.92877
epoch :  20  -  cost:  650.1423
epoch :  21  -  cost:  298.91248
epoch :  22  -  cost:  624.2649
epoch :  23  -  cost:  304.6526
epoch :  24  -  cost:  599.09265
epoch :  25  -  cost:  309.12912
epoch :  26  -  cost:  574.9874
epoch :  27  -  cost:  312.50696
epoch :  28  -  cost:  552.1724
epoch :  29  -  cost:  314.89877
epoch :  30  -  cost:  530.71924
epoch :  31  -  cost:  316.2555
epoch :  32  -  cost:  510.59436
epoch :  33  -  cost:  316.52396
epoch :  34  -  cost:  491.75363
epoch :  35  -  cost:  315.8363
epoch :  36  -  cost:  474.19672
epoch :  37  -  cost:  314.4753
epoch :  38  -  cost:  457.93027
epoch :  39  -  cost:  312.70132
epoch :  40  -  cost:  442.9085
epoch :  41  -  cost:  310.6492
epoch :  42  -  cost:  429.0223
epoch :  43  -  cost:  308.34808
epoch :  44  -  cost:  416.13553
epoch :  45  -  cost:  305.78522
epoch :  46  -  cost:  404.12265
epoch :  47  -  cost:  302.95117
epoch :  48  -  cost:  392.8836
epoch :  49  -  cost:  299.85803
epoch :  50  -  cost:  382.34164
epoch :  51  -  cost:  296.5417
epoch :  52  -  cost:  372.43466
epoch :  53  -  cost:  293.05508
epoch :  54  -  cost:  363.10812
epoch :  55  -  cost:  289.45724
epoch :  56  -  cost:  354.31015
epoch :  57  -  cost:  285.80283
epoch :  58  -  cost:  345.99075
epoch :  59  -  cost:  282.1344
epoch :  60  -  cost:  338.10217
epoch :  61  -  cost:  278.48007
epoch :  62  -  cost:  330.60144
epoch :  63  -  cost:  274.85562
epoch :  64  -  cost:  323.45273
epoch :  65  -  cost:  271.268
epoch :  66  -  cost:  316.62943
epoch :  67  -  cost:  267.7202
epoch :  68  -  cost:  310.1149
epoch :  69  -  cost:  264.21506
epoch :  70  -  cost:  303.90244
epoch :  71  -  cost:  260.75723
epoch :  72  -  cost:  297.9922
epoch :  73  -  cost:  257.35446
epoch :  74  -  cost:  292.3885
epoch :  75  -  cost:  254.01715
epoch :  76  -  cost:  287.0959
epoch :  77  -  cost:  250.75693
epoch :  78  -  cost:  282.1163
epoch :  79  -  cost:  247.58528
epoch :  80  -  cost:  277.44745
epoch :  81  -  cost:  244.51201
epoch :  82  -  cost:  273.08167
epoch :  83  -  cost:  241.5444
epoch :  84  -  cost:  269.0066
epoch :  85  -  cost:  238.68669
epoch :  86  -  cost:  265.20593
epoch :  87  -  cost:  235.94052
epoch :  88  -  cost:  261.66098
epoch :  89  -  cost:  233.30515
epoch :  90  -  cost:  258.35193
epoch :  91  -  cost:  230.77788
epoch :  92  -  cost:  255.2584
epoch :  93  -  cost:  228.35497
epoch :  94  -  cost:  252.36098
epoch :  95  -  cost:  226.03178
epoch :  96  -  cost:  249.64113
epoch :  97  -  cost:  223.80328
epoch :  98  -  cost:  247.0819
epoch :  99  -  cost:  221.66435

In [89]:
correct_prediction = tf.equal(tf.argmax(pred,1), tf.argmax(y,1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
print("Accuracy: ",(sess.run(accuracy, feed_dict={x: test_x, y: test_y})))

Accuracy:  0.5714286